"""
api.py

Minimal API exposing the Airfare Price Index, as required by the problem
statement: "...provide an API that the NSO and RBI can consume."

This reads the CSV outputs the pipeline already produces -- it does not
recompute anything. In a production system this would read from a database
instead of CSVs, but for a prototype this keeps it simple and transparent.

Run with:
    pip install fastapi uvicorn
    uvicorn api:app --reload

Then visit http://127.0.0.1:8000/docs for interactive API docs (auto-generated).
"""

import pandas as pd
from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from pathlib import Path

app = FastAPI(
    title="Airfare Price Index (APIx) API",
    description="Prototype API for NSO/RBI to consume airfare inflation index data.",
    version="0.1.0",
)

# Serves data/*.json (generated by export_static_data.py) at /data/*.json --
# this is what lets the SAME apix_dashboard.html work here (local, via
# uvicorn) and on GitHub Pages (fully static, no Python at all). Run
# export_static_data.py before starting this server.
_data_dir = Path(__file__).parent / "data"
if _data_dir.exists():
    app.mount("/data", StaticFiles(directory=str(_data_dir)), name="data")


def _read_csv_safe(path):
    try:
        return pd.read_csv(path)
    except FileNotFoundError:
        raise HTTPException(
            status_code=503,
            detail=f"{path} not found -- run main.py first to generate pipeline outputs.",
        )


@app.get("/", response_class=HTMLResponse)
def dashboard():
    """Serves the dashboard itself -- visit http://127.0.0.1:8000/ in a browser."""
    html_path = Path(__file__).parent / "apix_dashboard.html"
    if not html_path.exists():
        raise HTTPException(status_code=404, detail="apix_dashboard.html not found alongside api.py")
    return html_path.read_text()


@app.get("/api")
def api_info():
    return {
        "name": "Airfare Price Index (APIx) API",
        "note": "The dashboard itself is served statically from /data/*.json (see StaticFiles mount above). These /apix/* endpoints are the separate programmatic API for NSO/RBI to consume, as required by the problem statement.",
        "endpoints": [
            "/apix/daily", "/apix/weekly", "/apix/monthly",
            "/apix/routes", "/apix/heatmap", "/apix/elasticity", "/apix/latest",
        ],
    }


@app.get("/apix/latest")
def latest_index():
    """Single latest APIx value -- the number most consumers actually want."""
    df = _read_csv_safe("apix_daily.csv")
    latest_row = df.iloc[-1]
    return {
        "date": latest_row["scrape_date"],
        "apix": round(float(latest_row["APIx"]), 2),
        "base_period_note": "Index = 100 in the base period (first 7 days of data)",
    }


@app.get("/apix/daily")
def daily_index():
    df = _read_csv_safe("apix_daily.csv")
    return df.to_dict(orient="records")


@app.get("/apix/weekly")
def weekly_index():
    df = _read_csv_safe("apix_weekly.csv")
    return df.to_dict(orient="records")


@app.get("/apix/monthly")
def monthly_index():
    df = _read_csv_safe("apix_monthly.csv")
    return df.to_dict(orient="records")


@app.get("/apix/routes")
def route_breakdown():
    """Full per-day, per-route sub-index -- feeds custom analysis."""
    df = _read_csv_safe("apix_route_breakdown.csv")
    return df.to_dict(orient="records")


@app.get("/apix/heatmap")
def route_heatmap():
    """7-day average sub-index per route -- feeds the dashboard heatmap grid."""
    df = _read_csv_safe("apix_route_breakdown.csv")
    df["scrape_date"] = pd.to_datetime(df["scrape_date"])
    cutoff = df["scrape_date"].max() - pd.Timedelta(days=7)
    recent = df[df["scrape_date"] > cutoff]
    grouped = (
        recent.groupby(["origin", "destination"])["route_sub_index"]
        .mean()
        .round(1)
        .reset_index()
    )
    grouped["route"] = grouped["origin"] + "\u2013" + grouped["destination"]
    return grouped[["route", "route_sub_index"]].rename(
        columns={"route_sub_index": "v"}
    ).to_dict(orient="records")


@app.get("/apix/elasticity")
def lead_time_elasticity():
    """Average total fare by advance-purchase window -- feeds the elasticity chart."""
    df = _read_csv_safe("clean_airfare_quotes.csv")
    grouped = (
        df.groupby("advance_window_days")["total_fare"]
        .mean()
        .round(0)
        .reset_index()
        .sort_values("advance_window_days")
    )
    grouped["window"] = "T+" + grouped["advance_window_days"].astype(str)
    return grouped[["window", "total_fare"]].rename(
        columns={"total_fare": "fare"}
    ).to_dict(orient="records")
